/*************************************
This program can be used to evaluate a jboost-trained classifier on new data.
The code contains a single procedure:
  double predict(void **attr, double *ret)
The first argument attr is an array of pointers corresponding to the
attributes specified in the spec file.  Thus, if attribute i is text,
then attr[i] must be a char array; if attribute i is a number, then
*attr[i] must be a double; and if attribute i is finite, then *attr[i]
must be an int containing the index of the chosen value.  An undefined
attribute is indicated by setting attr[i] to NULL.
Specifically, these pointers are:
     index    attr.type    data.type   name
   ------------------------------------------
        0     number       double      H
        1     number       double      S
        2     number       double      V
The second argument ret is a pointer to an array of k doubles, where k
is the number of classes.  The scores for each of the k classes will
be stored in this array.  If ret is NULL, then no scores are stored.
In any case, predict returns the score for class 0 (=ret[0]).
These scores correspond to the classes as follows:
            index       class name
           ------------------------
               0        non-pipe
               1        pipe
This classifier was automatically generated by jboost on
Tue Feb 23 10:14:28 PST 2010.
*************************************/
double predict_pipe(void **attr, double *r)
{
    int i, j, h, a;
    HashTableEntry_t *entry;
    char *s;
    static char **words = NULL;
    static int max_word_list_size = 0;
    int num_words;
    static char *buffer = NULL;
    static int buffer_size = 0;
    char **pat;
    Prediction_t p;
    if (!hash_table)
    {
        hash_table = (HashTableEntry_t **)
                     malloc(hash_table_size * sizeof(HashTableEntry_t *));
        for (i = 0; i < hash_table_size; i++)
            hash_table[i] = NULL;
        for (i = 0; i < num_keys; i++)
        {
            h = hash(keys[i]);
            entry = (HashTableEntry_t *) malloc(sizeof(HashTableEntry_t));
            entry->key = keys[i];
            entry->id = i;
            entry->next = hash_table[h];
            hash_table[h] = entry;
        }
        for (i = 0; i < num_text_attr; i++)
            tokens[text_attr[i]] = (char *) malloc(num_keys * sizeof(char));
    }
    for (i = 0; i < num_text_attr; i++)
    {
        a = text_attr[i];
        if (!defined_attr(a))
            continue;
        for (j = 0; j < num_keys; j++)
            tokens[a][j] = 0;
        while ((int)strlcpy(buffer, (char*)attr[a], buffer_size) >= buffer_size)
        {
            buffer_size = 2 * strlen((char*)attr[a]);
            buffer = (char *) realloc(buffer, (buffer_size + 1) * sizeof(char));
        }
        num_words = 0;
        for (s = strtok(buffer, WHITE_CHARS); s; s = strtok(NULL, WHITE_CHARS))
        {
            if (num_words >= max_word_list_size)
            {
                max_word_list_size = 2 * max_word_list_size + 1;
                words = (char **) realloc(words, max_word_list_size * sizeof(char *));
            }
            words[num_words++] = s;
        }
        for (pat = text_patterns[i]; *pat; pat++)
        {
            set_pattern(num_words, words, *pat);
            while (more_tokens())
            {
                s = next_token();
                for (entry = hash_table[hash(s)]; entry; entry = entry->next)
                    if (!strcmp(entry->key, s))
                    {
                        tokens[a][entry->id] = 1;
                        break;
                    }
            }
        }
    }
    reset_pred();
    add_pred(   /* R */
        -1.2298782619778563);
    if (defined_attr(0))    /* R.0 */
    {
        if (double_attr(0) <= 91.5)
        {
            add_pred(   /* R.0:0 */
                -2.173557927932845);
        }
        else
        {
            add_pred(   /* R.0:1 */
                0.9680467028594667);
            if (defined_attr(0))    /* R.0:1.0 */
            {
                if (double_attr(0) <= 160.5)
                {
                    add_pred(   /* R.0:1.0:0 */
                        0.3261245541392819);
                    if (defined_attr(1))    /* R.0:1.0:0.0 */
                    {
                        if (double_attr(1) <= 81.5)
                        {
                            add_pred(   /* R.0:1.0:0.0:0 */
                                -0.3068552329589368);
                            if (defined_attr(0))    /* R.0:1.0:0.0:0.0 */
                            {
                                if (double_attr(0) <= 101.5)
                                {
                                    add_pred(   /* R.0:1.0:0.0:0.0:0 */
                                        -0.9059780896061521);
                                    if (defined_attr(1))    /* R.0:1.0:0.0:0.0:0.0 */
                                    {
                                        if (double_attr(1) <= 21.5)
                                        {
                                            add_pred(   /* R.0:1.0:0.0:0.0:0.0:0 */
                                                -3.3201251883455174);
                                        }
                                        else
                                        {
                                            add_pred(   /* R.0:1.0:0.0:0.0:0.0:1 */
                                                -0.13817190624892667);
                                        }
                                    }
                                }
                                else
                                {
                                    add_pred(   /* R.0:1.0:0.0:0.0:1 */
                                        1.0024759624470976);
                                    if (defined_attr(1))    /* R.0:1.0:0.0:0.0:1.0 */
                                    {
                                        if (double_attr(1) <= 5.5)
                                        {
                                            add_pred(   /* R.0:1.0:0.0:0.0:1.0:0 */
                                                -0.7154317269609707);
                                            if (defined_attr(2))    /* R.0:1.0:0.0:0.0:1.0:0.0 */
                                            {
                                                if (double_attr(2) <= 218.5)
                                                {
                                                    add_pred(   /* R.0:1.0:0.0:0.0:1.0:0.0:0 */
                                                        0.03615755129503506);
                                                }
                                                else
                                                {
                                                    add_pred(   /* R.0:1.0:0.0:0.0:1.0:0.0:1 */
                                                        -2.436310334378314);
                                                }
                                            }
                                            if (defined_attr(1))    /* R.0:1.0:0.0:0.0:1.0:0.1 */
                                            {
                                                if (double_attr(1) <= 2.5)
                                                {
                                                    add_pred(   /* R.0:1.0:0.0:0.0:1.0:0.1:0 */
                                                        -0.8121877640105349);
                                                }
                                                else
                                                {
                                                    add_pred(   /* R.0:1.0:0.0:0.0:1.0:0.1:1 */
                                                        0.30398598309047514);
                                                }
                                            }
                                        }
                                        else
                                        {
                                            add_pred(   /* R.0:1.0:0.0:0.0:1.0:1 */
                                                0.5713603031507887);
                                            if (defined_attr(2))    /* R.0:1.0:0.0:0.0:1.0:1.0 */
                                            {
                                                if (double_attr(2) <= 193.5)
                                                {
                                                    add_pred(   /* R.0:1.0:0.0:0.0:1.0:1.0:0 */
                                                        -0.5061399923254128);
                                                }
                                                else
                                                {
                                                    add_pred(   /* R.0:1.0:0.0:0.0:1.0:1.0:1 */
                                                        0.9898332882185832);
                                                    if (defined_attr(0))    /* R.0:1.0:0.0:0.0:1.0:1.0:1.0 */
                                                    {
                                                        if (double_attr(0) <= 108.5)
                                                        {
                                                            add_pred(   /* R.0:1.0:0.0:0.0:1.0:1.0:1.0:0 */
                                                                -1.5946011217348692);
                                                        }
                                                        else
                                                        {
                                                            add_pred(   /* R.0:1.0:0.0:0.0:1.0:1.0:1.0:1 */
                                                                0.7058779721623453);
                                                            if (defined_attr(0))    /* R.0:1.0:0.0:0.0:1.0:1.0:1.0:1.0 */
                                                            {
                                                                if (double_attr(0) <= 146.5)
                                                                {
                                                                    add_pred(   /* R.0:1.0:0.0:0.0:1.0:1.0:1.0:1.0:0 */
                                                                        0.7316792533446826);
                                                                }
                                                                else
                                                                {
                                                                    add_pred(   /* R.0:1.0:0.0:0.0:1.0:1.0:1.0:1.0:1 */
                                                                        -1.5119876382038027);
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                            if (defined_attr(2))    /* R.0:1.0:0.0:0.1 */
                            {
                                if (double_attr(2) <= 79.5)
                                {
                                    add_pred(   /* R.0:1.0:0.0:0.1:0 */
                                        -2.3569505367990997);
                                }
                                else
                                {
                                    add_pred(   /* R.0:1.0:0.0:0.1:1 */
                                        0.10474084380248314);
                                }
                            }
                        }
                        else
                        {
                            add_pred(   /* R.0:1.0:0.0:1 */
                                2.0280007485739446);
                            if (defined_attr(0))    /* R.0:1.0:0.0:1.0 */
                            {
                                if (double_attr(0) <= 93.5)
                                {
                                    add_pred(   /* R.0:1.0:0.0:1.0:0 */
                                        -0.665023050418556);
                                }
                                else
                                {
                                    add_pred(   /* R.0:1.0:0.0:1.0:1 */
                                        0.3539079254794245);
                                    if (defined_attr(2))    /* R.0:1.0:0.0:1.0:1.0 */
                                    {
                                        if (double_attr(2) <= 18.5)
                                        {
                                            add_pred(   /* R.0:1.0:0.0:1.0:1.0:0 */
                                                -1.4865284508583265);
                                        }
                                        else
                                        {
                                            add_pred(   /* R.0:1.0:0.0:1.0:1.0:1 */
                                                0.434515283451618);
                                            if (defined_attr(1))    /* R.0:1.0:0.0:1.0:1.0:1.0 */
                                            {
                                                if (double_attr(1) <= 113.5)
                                                {
                                                    add_pred(   /* R.0:1.0:0.0:1.0:1.0:1.0:0 */
                                                        -0.04111037375763089);
                                                }
                                                else
                                                {
                                                    add_pred(   /* R.0:1.0:0.0:1.0:1.0:1.0:1 */
                                                        1.5374617558706662);
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                else
                {
                    add_pred(   /* R.0:1.0:1 */
                        -3.868027143264421);
                }
            }
            if (defined_attr(2))    /* R.0:1.1 */
            {
                if (double_attr(2) <= 63.5)
                {
                    add_pred(   /* R.0:1.1:0 */
                        -1.1842655589568079);
                    if (defined_attr(1))    /* R.0:1.1:0.0 */
                    {
                        if (double_attr(1) <= 124.5)
                        {
                            add_pred(   /* R.0:1.1:0.0:0 */
                                -1.8653369342625683);
                        }
                        else
                        {
                            add_pred(   /* R.0:1.1:0.0:1 */
                                -0.08538509521785317);
                        }
                    }
                }
                else
                {
                    add_pred(   /* R.0:1.1:1 */
                        0.048964943222706926);
                }
            }
        }
    }
    if (defined_attr(0))    /* R.1 */
    {
        if (double_attr(0) <= 95.5)
        {
            add_pred(   /* R.1:0 */
                -0.953627514021705);
            if (defined_attr(0))    /* R.1:0.0 */
            {
                if (double_attr(0) <= 34.5)
                {
                    add_pred(   /* R.1:0.0:0 */
                        -1.5545769733347075);
                }
                else
                {
                    add_pred(   /* R.1:0.0:1 */
                        0.3680744520205484);
                    if (defined_attr(1))    /* R.1:0.0:1.0 */
                    {
                        if (double_attr(1) <= 48.5)
                        {
                            add_pred(   /* R.1:0.0:1.0:0 */
                                -1.4660989960558295);
                        }
                        else
                        {
                            add_pred(   /* R.1:0.0:1.0:1 */
                                0.6778456329405187);
                            if (defined_attr(2))    /* R.1:0.0:1.0:1.0 */
                            {
                                if (double_attr(2) <= 177.5)
                                {
                                    add_pred(   /* R.1:0.0:1.0:1.0:0 */
                                        -0.1778020878339021);
                                    if (defined_attr(1))    /* R.1:0.0:1.0:1.0:0.0 */
                                    {
                                        if (double_attr(1) <= 62.5)
                                        {
                                            add_pred(   /* R.1:0.0:1.0:1.0:0.0:0 */
                                                -1.4717337494369145);
                                        }
                                        else
                                        {
                                            add_pred(   /* R.1:0.0:1.0:1.0:0.0:1 */
                                                0.378823637111304);
                                        }
                                    }
                                    if (defined_attr(2))    /* R.1:0.0:1.0:1.0:0.1 */
                                    {
                                        if (double_attr(2) <= 166.5)
                                        {
                                            add_pred(   /* R.1:0.0:1.0:1.0:0.1:0 */
                                                -0.13339973755917106);
                                        }
                                        else
                                        {
                                            add_pred(   /* R.1:0.0:1.0:1.0:0.1:1 */
                                                0.8295197656026982);
                                        }
                                    }
                                }
                                else
                                {
                                    add_pred(   /* R.1:0.0:1.0:1.0:1 */
                                        1.120203966651109);
                                    if (defined_attr(1))    /* R.1:0.0:1.0:1.0:1.0 */
                                    {
                                        if (double_attr(1) <= 83.5)
                                        {
                                            add_pred(   /* R.1:0.0:1.0:1.0:1.0:0 */
                                                2.002957475781704);
                                            if (defined_attr(0))    /* R.1:0.0:1.0:1.0:1.0:0.0 */
                                            {
                                                if (double_attr(0) <= 50.5)
                                                {
                                                    add_pred(   /* R.1:0.0:1.0:1.0:1.0:0.0:0 */
                                                        2.156704493809261);
                                                    if (defined_attr(0))    /* R.1:0.0:1.0:1.0:1.0:0.0:0.0 */
                                                    {
                                                        if (double_attr(0) <= 36.5)
                                                        {
                                                            add_pred(   /* R.1:0.0:1.0:1.0:1.0:0.0:0.0:0 */
                                                                -3.2586982387768106);
                                                        }
                                                        else
                                                        {
                                                            add_pred(   /* R.1:0.0:1.0:1.0:1.0:0.0:0.0:1 */
                                                                2.315026924955563);
                                                        }
                                                    }
                                                }
                                                else
                                                {
                                                    add_pred(   /* R.1:0.0:1.0:1.0:1.0:0.0:1 */
                                                        -1.8520380309999982);
                                                    if (defined_attr(1))    /* R.1:0.0:1.0:1.0:1.0:0.0:1.0 */
                                                    {
                                                        if (double_attr(1) <= 61.0)
                                                        {
                                                            add_pred(   /* R.1:0.0:1.0:1.0:1.0:0.0:1.0:0 */
                                                                -1.5180414067223114);
                                                        }
                                                        else
                                                        {
                                                            add_pred(   /* R.1:0.0:1.0:1.0:1.0:0.0:1.0:1 */
                                                                -0.18921480967470936);
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                        else
                                        {
                                            add_pred(   /* R.1:0.0:1.0:1.0:1.0:1 */
                                                -3.1468385435763593);
                                        }
                                    }
                                }
                            }
                            if (defined_attr(0))    /* R.1:0.0:1.0:1.1 */
                            {
                                if (double_attr(0) <= 49.5)
                                {
                                    add_pred(   /* R.1:0.0:1.0:1.1:0 */
                                        0.8002812822692755);
                                    if (defined_attr(1))    /* R.1:0.0:1.0:1.1:0.0 */
                                    {
                                        if (double_attr(1) <= 91.5)
                                        {
                                            add_pred(   /* R.1:0.0:1.0:1.1:0.0:0 */
                                                1.6785162527900475);
                                            if (defined_attr(2))    /* R.1:0.0:1.0:1.1:0.0:0.0 */
                                            {
                                                if (double_attr(2) <= 210.5)
                                                {
                                                    add_pred(   /* R.1:0.0:1.0:1.1:0.0:0.0:0 */
                                                        1.39407073833509);
                                                    if (defined_attr(2))    /* R.1:0.0:1.0:1.1:0.0:0.0:0.0 */
                                                    {
                                                        if (double_attr(2) <= 135.5)
                                                        {
                                                            add_pred(   /* R.1:0.0:1.0:1.1:0.0:0.0:0.0:0 */
                                                                -2.3415915548526556);
                                                        }
                                                        else
                                                        {
                                                            add_pred(   /* R.1:0.0:1.0:1.1:0.0:0.0:0.0:1 */
                                                                1.3076214890429678);
                                                            if (defined_attr(1))    /* R.1:0.0:1.0:1.1:0.0:0.0:0.0:1.0 */
                                                            {
                                                                if (double_attr(1) <= 57.5)
                                                                {
                                                                    add_pred(   /* R.1:0.0:1.0:1.1:0.0:0.0:0.0:1.0:0 */
                                                                        -1.4744339129907018);
                                                                }
                                                                else
                                                                {
                                                                    add_pred(   /* R.1:0.0:1.0:1.1:0.0:0.0:0.0:1.0:1 */
                                                                        2.307399187590274);
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                                else
                                                {
                                                    add_pred(   /* R.1:0.0:1.0:1.1:0.0:0.0:1 */
                                                        -0.6726011001660767);
                                                }
                                            }
                                        }
                                        else
                                        {
                                            add_pred(   /* R.1:0.0:1.0:1.1:0.0:1 */
                                                -3.297452474456832);
                                        }
                                    }
                                }
                                else
                                {
                                    add_pred(   /* R.1:0.0:1.0:1.1:1 */
                                        0.062024034356182756);
                                    if (defined_attr(1))    /* R.1:0.0:1.0:1.1:1.0 */
                                    {
                                        if (double_attr(1) <= 92.5)
                                        {
                                            add_pred(   /* R.1:0.0:1.0:1.1:1.0:0 */
                                                -0.297812710851997);
                                            if (defined_attr(0))    /* R.1:0.0:1.0:1.1:1.0:0.0 */
                                            {
                                                if (double_attr(0) <= 93.5)
                                                {
                                                    add_pred(   /* R.1:0.0:1.0:1.1:1.0:0.0:0 */
                                                        -0.7354366897802509);
                                                }
                                                else
                                                {
                                                    add_pred(   /* R.1:0.0:1.0:1.1:1.0:0.0:1 */
                                                        0.8128501596468893);
                                                }
                                            }
                                            if (defined_attr(0))    /* R.1:0.0:1.0:1.1:1.0:0.1 */
                                            {
                                                if (double_attr(0) <= 92.5)
                                                {
                                                    add_pred(   /* R.1:0.0:1.0:1.1:1.0:0.1:0 */
                                                        -0.6538121726938811);
                                                    if (defined_attr(2))    /* R.1:0.0:1.0:1.1:1.0:0.1:0.0 */
                                                    {
                                                        if (double_attr(2) <= 87.5)
                                                        {
                                                            add_pred(   /* R.1:0.0:1.0:1.1:1.0:0.1:0.0:0 */
                                                                0.5491990368120745);
                                                        }
                                                        else
                                                        {
                                                            add_pred(   /* R.1:0.0:1.0:1.1:1.0:0.1:0.0:1 */
                                                                -0.6010443309494912);
                                                        }
                                                    }
                                                }
                                                else
                                                {
                                                    add_pred(   /* R.1:0.0:1.0:1.1:1.0:0.1:1 */
                                                        0.19204916376597553);
                                                    if (defined_attr(2))    /* R.1:0.0:1.0:1.1:1.0:0.1:1.0 */
                                                    {
                                                        if (double_attr(2) <= 136.5)
                                                        {
                                                            add_pred(   /* R.1:0.0:1.0:1.1:1.0:0.1:1.0:0 */
                                                                -0.4583279092381053);
                                                        }
                                                        else
                                                        {
                                                            add_pred(   /* R.1:0.0:1.0:1.1:1.0:0.1:1.0:1 */
                                                                0.5512948404001645);
                                                            if (defined_attr(1))    /* R.1:0.0:1.0:1.1:1.0:0.1:1.0:1.0 */
                                                            {
                                                                if (double_attr(1) <= 57.5)
                                                                {
                                                                    add_pred(   /* R.1:0.0:1.0:1.1:1.0:0.1:1.0:1.0:0 */
                                                                        -0.8784396028914009);
                                                                }
                                                                else
                                                                {
                                                                    add_pred(   /* R.1:0.0:1.0:1.1:1.0:0.1:1.0:1.0:1 */
                                                                        0.8400662308183466);
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                        else
                                        {
                                            add_pred(   /* R.1:0.0:1.0:1.1:1.0:1 */
                                                1.0571543853743421);
                                        }
                                    }
                                }
                            }
                        }
                    }
                    if (defined_attr(0))    /* R.1:0.0:1.1 */
                    {
                        if (double_attr(0) <= 94.5)
                        {
                            add_pred(   /* R.1:0.0:1.1:0 */
                                -0.10849777220228646);
                        }
                        else
                        {
                            add_pred(   /* R.1:0.0:1.1:1 */
                                0.9188379263858246);
                            if (defined_attr(2))    /* R.1:0.0:1.1:1.0 */
                            {
                                if (double_attr(2) <= 103.5)
                                {
                                    add_pred(   /* R.1:0.0:1.1:1.0:0 */
                                        0.9832809397052059);
                                    if (defined_attr(2))    /* R.1:0.0:1.1:1.0:0.0 */
                                    {
                                        if (double_attr(2) <= 60.5)
                                        {
                                            add_pred(   /* R.1:0.0:1.1:1.0:0.0:0 */
                                                -1.202950663234224);
                                        }
                                        else
                                        {
                                            add_pred(   /* R.1:0.0:1.1:1.0:0.0:1 */
                                                1.1744958290204526);
                                        }
                                    }
                                    if (defined_attr(2))    /* R.1:0.0:1.1:1.0:0.1 */
                                    {
                                        if (double_attr(2) <= 90.5)
                                        {
                                            add_pred(   /* R.1:0.0:1.1:1.0:0.1:0 */
                                                -0.6791113388343766);
                                        }
                                        else
                                        {
                                            add_pred(   /* R.1:0.0:1.1:1.0:0.1:1 */
                                                0.761364803213484);
                                        }
                                    }
                                }
                                else
                                {
                                    add_pred(   /* R.1:0.0:1.1:1.0:1 */
                                        -0.2297161769209708);
                                }
                            }
                        }
                    }
                }
            }
            if (defined_attr(1))    /* R.1:0.1 */
            {
                if (double_attr(1) <= 66.5)
                {
                    add_pred(   /* R.1:0.1:0 */
                        -0.48442014829727786);
                    if (defined_attr(1))    /* R.1:0.1:0.0 */
                    {
                        if (double_attr(1) <= 4.5)
                        {
                            add_pred(   /* R.1:0.1:0.0:0 */
                                0.7502295170150667);
                            if (defined_attr(2))    /* R.1:0.1:0.0:0.0 */
                            {
                                if (double_attr(2) <= 214.5)
                                {
                                    add_pred(   /* R.1:0.1:0.0:0.0:0 */
                                        1.2259445638025055);
                                    if (defined_attr(0))    /* R.1:0.1:0.0:0.0:0.0 */
                                    {
                                        if (double_attr(0) <= 57.5)
                                        {
                                            add_pred(   /* R.1:0.1:0.0:0.0:0.0:0 */
                                                0.8863135359727724);
                                        }
                                        else
                                        {
                                            add_pred(   /* R.1:0.1:0.0:0.0:0.0:1 */
                                                -1.8286067769528442);
                                        }
                                    }
                                }
                                else
                                {
                                    add_pred(   /* R.1:0.1:0.0:0.0:1 */
                                        -1.6289408658560705);
                                }
                            }
                            if (defined_attr(2))    /* R.1:0.1:0.0:0.1 */
                            {
                                if (double_attr(2) <= 211.5)
                                {
                                    add_pred(   /* R.1:0.1:0.0:0.1:0 */
                                        0.8244539852122852);
                                    if (defined_attr(2))    /* R.1:0.1:0.0:0.1:0.0 */
                                    {
                                        if (double_attr(2) <= 205.5)
                                        {
                                            add_pred(   /* R.1:0.1:0.0:0.1:0.0:0 */
                                                -1.7140659686296595);
                                        }
                                        else
                                        {
                                            add_pred(   /* R.1:0.1:0.0:0.1:0.0:1 */
                                                0.5879951678824982);
                                        }
                                    }
                                }
                                else
                                {
                                    add_pred(   /* R.1:0.1:0.0:0.1:1 */
                                        -0.22269218225890183);
                                }
                            }
                            if (defined_attr(0))    /* R.1:0.1:0.0:0.2 */
                            {
                                if (double_attr(0) <= 57.5)
                                {
                                    add_pred(   /* R.1:0.1:0.0:0.2:0 */
                                        0.18262900592627992);
                                }
                                else
                                {
                                    add_pred(   /* R.1:0.1:0.0:0.2:1 */
                                        -1.5030813955277391);
                                }
                            }
                        }
                        else
                        {
                            add_pred(   /* R.1:0.1:0.0:1 */
                                -0.7170126521459481);
                            if (defined_attr(0))    /* R.1:0.1:0.0:1.0 */
                            {
                                if (double_attr(0) <= 40.5)
                                {
                                    add_pred(   /* R.1:0.1:0.0:1.0:0 */
                                        -2.663575686932573);
                                }
                                else
                                {
                                    add_pred(   /* R.1:0.1:0.0:1.0:1 */
                                        -0.03950383682051725);
                                    if (defined_attr(1))    /* R.1:0.1:0.0:1.0:1.0 */
                                    {
                                        if (double_attr(1) <= 24.5)
                                        {
                                            add_pred(   /* R.1:0.1:0.0:1.0:1.0:0 */
                                                -1.5915531741030768);
                                        }
                                        else
                                        {
                                            add_pred(   /* R.1:0.1:0.0:1.0:1.0:1 */
                                                0.26844430440080036);
                                            if (defined_attr(2))    /* R.1:0.1:0.0:1.0:1.0:1.0 */
                                            {
                                                if (double_attr(2) <= 214.5)
                                                {
                                                    add_pred(   /* R.1:0.1:0.0:1.0:1.0:1.0:0 */
                                                        0.011741441283213345);
                                                }
                                                else
                                                {
                                                    add_pred(   /* R.1:0.1:0.0:1.0:1.0:1.0:1 */
                                                        1.291003869373598);
                                                    if (defined_attr(1))    /* R.1:0.1:0.0:1.0:1.0:1.0:1.0 */
                                                    {
                                                        if (double_attr(1) <= 45.5)
                                                        {
                                                            add_pred(   /* R.1:0.1:0.0:1.0:1.0:1.0:1.0:0 */
                                                                -1.3453070010213946);
                                                        }
                                                        else
                                                        {
                                                            add_pred(   /* R.1:0.1:0.0:1.0:1.0:1.0:1.0:1 */
                                                                2.934206569870237);
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                else
                {
                    add_pred(   /* R.1:0.1:1 */
                        0.4557775288264182);
                    if (defined_attr(0))    /* R.1:0.1:1.0 */
                    {
                        if (double_attr(0) <= 86.5)
                        {
                            add_pred(   /* R.1:0.1:1.0:0 */
                                -0.7276036976921381);
                            if (defined_attr(1))    /* R.1:0.1:1.0:0.0 */
                            {
                                if (double_attr(1) <= 91.5)
                                {
                                    add_pred(   /* R.1:0.1:1.0:0.0:0 */
                                        0.06752032650250564);
                                    if (defined_attr(2))    /* R.1:0.1:1.0:0.0:0.0 */
                                    {
                                        if (double_attr(2) <= 213.5)
                                        {
                                            add_pred(   /* R.1:0.1:1.0:0.0:0.0:0 */
                                                0.52589722222859);
                                            if (defined_attr(0))    /* R.1:0.1:1.0:0.0:0.0:0.0 */
                                            {
                                                if (double_attr(0) <= 48.5)
                                                {
                                                    add_pred(   /* R.1:0.1:1.0:0.0:0.0:0.0:0 */
                                                        0.5180626496772732);
                                                    if (defined_attr(0))    /* R.1:0.1:1.0:0.0:0.0:0.0:0.0 */
                                                    {
                                                        if (double_attr(0) <= 30.5)
                                                        {
                                                            add_pred(   /* R.1:0.1:1.0:0.0:0.0:0.0:0.0:0 */
                                                                -1.5862905594002141);
                                                        }
                                                        else
                                                        {
                                                            add_pred(   /* R.1:0.1:1.0:0.0:0.0:0.0:0.0:1 */
                                                                0.6302712196715771);
                                                            if (defined_attr(2))    /* R.1:0.1:1.0:0.0:0.0:0.0:0.0:1.0 */
                                                            {
                                                                if (double_attr(2) <= 139.0)
                                                                {
                                                                    add_pred(   /* R.1:0.1:1.0:0.0:0.0:0.0:0.0:1.0:0 */
                                                                        -1.4146073481908694);
                                                                }
                                                                else
                                                                {
                                                                    add_pred(   /* R.1:0.1:1.0:0.0:0.0:0.0:0.0:1.0:1 */
                                                                        1.5369918343483862);
                                                                    if (defined_attr(2))    /* R.1:0.1:1.0:0.0:0.0:0.0:0.0:1.0:1.0 */
                                                                    {
                                                                        if (double_attr(2) <= 196.5)
                                                                        {
                                                                            add_pred(   /* R.1:0.1:1.0:0.0:0.0:0.0:0.0:1.0:1.0:0 */
                                                                                1.8754709178550912);
                                                                            if (defined_attr(1))    /* R.1:0.1:1.0:0.0:0.0:0.0:0.0:1.0:1.0:0.0 */
                                                                            {
                                                                                if (double_attr(1) <= 72.5)
                                                                                {
                                                                                    add_pred(   /* R.1:0.1:1.0:0.0:0.0:0.0:0.0:1.0:1.0:0.0:0 */
                                                                                        0.9350845944222375);
                                                                                }
                                                                                else
                                                                                {
                                                                                    add_pred(   /* R.1:0.1:1.0:0.0:0.0:0.0:0.0:1.0:1.0:0.0:1 */
                                                                                        3.2115825244096676);
                                                                                }
                                                                            }
                                                                        }
                                                                        else
                                                                        {
                                                                            add_pred(   /* R.1:0.1:1.0:0.0:0.0:0.0:0.0:1.0:1.0:1 */
                                                                                -0.9850422716518533);
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                                else
                                                {
                                                    add_pred(   /* R.1:0.1:1.0:0.0:0.0:0.0:1 */
                                                        -1.616890585674905);
                                                }
                                            }
                                        }
                                        else
                                        {
                                            add_pred(   /* R.1:0.1:1.0:0.0:0.0:1 */
                                                -1.8437253988710949);
                                        }
                                    }
                                }
                                else
                                {
                                    add_pred(   /* R.1:0.1:1.0:0.0:1 */
                                        -2.0582118142581103);
                                }
                            }
                        }
                        else
                        {
                            add_pred(   /* R.1:0.1:1.0:1 */
                                0.35672735755136337);
                            if (defined_attr(1))    /* R.1:0.1:1.0:1.0 */
                            {
                                if (double_attr(1) <= 166.5)
                                {
                                    add_pred(   /* R.1:0.1:1.0:1.0:0 */
                                        -0.06643726062776344);
                                }
                                else
                                {
                                    add_pred(   /* R.1:0.1:1.0:1.0:1 */
                                        1.4016799018606958);
                                    if (defined_attr(1))    /* R.1:0.1:1.0:1.0:1.0 */
                                    {
                                        if (double_attr(1) <= 248.0)
                                        {
                                            add_pred(   /* R.1:0.1:1.0:1.0:1.0:0 */
                                                1.4749076207023133);
                                            if (defined_attr(2))    /* R.1:0.1:1.0:1.0:1.0:0.0 */
                                            {
                                                if (double_attr(2) <= 30.5)
                                                {
                                                    add_pred(   /* R.1:0.1:1.0:1.0:1.0:0.0:0 */
                                                        1.3474333419231814);
                                                }
                                                else
                                                {
                                                    add_pred(   /* R.1:0.1:1.0:1.0:1.0:0.0:1 */
                                                        -0.1991733872296843);
                                                }
                                            }
                                        }
                                        else
                                        {
                                            add_pred(   /* R.1:0.1:1.0:1.0:1.0:1 */
                                                -1.0527317130600284);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        else
        {
            add_pred(   /* R.1:1 */
                0.6196972065340168);
            if (defined_attr(0))    /* R.1:1.0 */
            {
                if (double_attr(0) <= 133.5)
                {
                    add_pred(   /* R.1:1.0:0 */
                        0.899966645784607);
                    if (defined_attr(1))    /* R.1:1.0:0.0 */
                    {
                        if (double_attr(1) <= 43.5)
                        {
                            add_pred(   /* R.1:1.0:0.0:0 */
                                -0.6573224198571738);
                            if (defined_attr(2))    /* R.1:1.0:0.0:0.0 */
                            {
                                if (double_attr(2) <= 173.0)
                                {
                                    add_pred(   /* R.1:1.0:0.0:0.0:0 */
                                        -1.1422675841379577);
                                    if (defined_attr(1))    /* R.1:1.0:0.0:0.0:0.0 */
                                    {
                                        if (double_attr(1) <= 27.5)
                                        {
                                            add_pred(   /* R.1:1.0:0.0:0.0:0.0:0 */
                                                -2.2642296880438786);
                                        }
                                        else
                                        {
                                            add_pred(   /* R.1:1.0:0.0:0.0:0.0:1 */
                                                -0.1817489043869111);
                                        }
                                    }
                                }
                                else
                                {
                                    add_pred(   /* R.1:1.0:0.0:0.0:1 */
                                        0.4633569295961132);
                                    if (defined_attr(1))    /* R.1:1.0:0.0:0.0:1.0 */
                                    {
                                        if (double_attr(1) <= 31.5)
                                        {
                                            add_pred(   /* R.1:1.0:0.0:0.0:1.0:0 */
                                                -0.5003886029814283);
                                        }
                                        else
                                        {
                                            add_pred(   /* R.1:1.0:0.0:0.0:1.0:1 */
                                                1.409821977554556);
                                            if (defined_attr(0))    /* R.1:1.0:0.0:0.0:1.0:1.0 */
                                            {
                                                if (double_attr(0) <= 97.0)
                                                {
                                                    add_pred(   /* R.1:1.0:0.0:0.0:1.0:1.0:0 */
                                                        -0.8199677172312925);
                                                }
                                                else
                                                {
                                                    add_pred(   /* R.1:1.0:0.0:0.0:1.0:1.0:1 */
                                                        1.541608533774522);
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                        else
                        {
                            add_pred(   /* R.1:1.0:0.0:1 */
                                2.530079463044545);
                            if (defined_attr(0))    /* R.1:1.0:0.0:1.0 */
                            {
                                if (double_attr(0) <= 98.5)
                                {
                                    add_pred(   /* R.1:1.0:0.0:1.0:0 */
                                        -0.47782178468301584);
                                    if (defined_attr(1))    /* R.1:1.0:0.0:1.0:0.0 */
                                    {
                                        if (double_attr(1) <= 47.5)
                                        {
                                            add_pred(   /* R.1:1.0:0.0:1.0:0.0:0 */
                                                -1.5712386520976414);
                                        }
                                        else
                                        {
                                            add_pred(   /* R.1:1.0:0.0:1.0:0.0:1 */
                                                0.03289783812851757);
                                        }
                                    }
                                }
                                else
                                {
                                    add_pred(   /* R.1:1.0:0.0:1.0:1 */
                                        0.7016817833215778);
                                    if (defined_attr(2))    /* R.1:1.0:0.0:1.0:1.0 */
                                    {
                                        if (double_attr(2) <= 76.5)
                                        {
                                            add_pred(   /* R.1:1.0:0.0:1.0:1.0:0 */
                                                -1.144524854147699);
                                        }
                                        else
                                        {
                                            add_pred(   /* R.1:1.0:0.0:1.0:1.0:1 */
                                                1.3701144570808101);
                                        }
                                    }
                                }
                            }
                        }
                    }
                    if (defined_attr(1))    /* R.1:1.0:0.1 */
                    {
                        if (double_attr(1) <= 14.5)
                        {
                            add_pred(   /* R.1:1.0:0.1:0 */
                                -1.7117595767025535);
                            if (defined_attr(0))    /* R.1:1.0:0.1:0.0 */
                            {
                                if (double_attr(0) <= 114.5)
                                {
                                    add_pred(   /* R.1:1.0:0.1:0.0:0 */
                                        -4.109699485938866);
                                }
                                else
                                {
                                    add_pred(   /* R.1:1.0:0.1:0.0:1 */
                                        0.17160973752788405);
                                }
                            }
                        }
                        else
                        {
                            add_pred(   /* R.1:1.0:0.1:1 */
                                1.146824501091834);
                            if (defined_attr(2))    /* R.1:1.0:0.1:1.0 */
                            {
                                if (double_attr(2) <= 83.5)
                                {
                                    add_pred(   /* R.1:1.0:0.1:1.0:0 */
                                        -2.4404064647826513);
                                }
                                else
                                {
                                    add_pred(   /* R.1:1.0:0.1:1.0:1 */
                                        0.5030725697762588);
                                    if (defined_attr(1))    /* R.1:1.0:0.1:1.0:1.0 */
                                    {
                                        if (double_attr(1) <= 63.5)
                                        {
                                            add_pred(   /* R.1:1.0:0.1:1.0:1.0:0 */
                                                -0.06767161690914716);
                                            if (defined_attr(0))    /* R.1:1.0:0.1:1.0:1.0:0.0 */
                                            {
                                                if (double_attr(0) <= 96.5)
                                                {
                                                    add_pred(   /* R.1:1.0:0.1:1.0:1.0:0.0:0 */
                                                        -2.036377484068203);
                                                    if (defined_attr(1))    /* R.1:1.0:0.1:1.0:1.0:0.0:0.0 */
                                                    {
                                                        if (double_attr(1) <= 56.0)
                                                        {
                                                            add_pred(   /* R.1:1.0:0.1:1.0:1.0:0.0:0.0:0 */
                                                                -2.0314673890469197);
                                                            if (defined_attr(2))    /* R.1:1.0:0.1:1.0:1.0:0.0:0.0:0.0 */
                                                            {
                                                                if (double_attr(2) <= 127.0)
                                                                {
                                                                    add_pred(   /* R.1:1.0:0.1:1.0:1.0:0.0:0.0:0.0:0 */
                                                                        -0.23329804513308872);
                                                                }
                                                                else
                                                                {
                                                                    add_pred(   /* R.1:1.0:0.1:1.0:1.0:0.0:0.0:0.0:1 */
                                                                        -1.9187651878976009);
                                                                }
                                                            }
                                                        }
                                                        else
                                                        {
                                                            add_pred(   /* R.1:1.0:0.1:1.0:1.0:0.0:0.0:1 */
                                                                -0.12982203045084845);
                                                        }
                                                    }
                                                }
                                                else
                                                {
                                                    add_pred(   /* R.1:1.0:0.1:1.0:1.0:0.0:1 */
                                                        0.04826230156803185);
                                                    if (defined_attr(1))    /* R.1:1.0:0.1:1.0:1.0:0.0:1.0 */
                                                    {
                                                        if (double_attr(1) <= 53.5)
                                                        {
                                                            add_pred(   /* R.1:1.0:0.1:1.0:1.0:0.0:1.0:0 */
                                                                -0.012316183499191754);
                                                            if (defined_attr(2))    /* R.1:1.0:0.1:1.0:1.0:0.0:1.0:0.0 */
                                                            {
                                                                if (double_attr(2) <= 96.5)
                                                                {
                                                                    add_pred(   /* R.1:1.0:0.1:1.0:1.0:0.0:1.0:0.0:0 */
                                                                        -1.606096577623581);
                                                                }
                                                                else
                                                                {
                                                                    add_pred(   /* R.1:1.0:0.1:1.0:1.0:0.0:1.0:0.0:1 */
                                                                        0.056738220474530324);
                                                                }
                                                            }
                                                        }
                                                        else
                                                        {
                                                            add_pred(   /* R.1:1.0:0.1:1.0:1.0:0.0:1.0:1 */
                                                                1.8856633042625106);
                                                        }
                                                    }
                                                    if (defined_attr(1))    /* R.1:1.0:0.1:1.0:1.0:0.0:1.1 */
                                                    {
                                                        if (double_attr(1) <= 24.5)
                                                        {
                                                            add_pred(   /* R.1:1.0:0.1:1.0:1.0:0.0:1.1:0 */
                                                                -1.2890527243527041);
                                                        }
                                                        else
                                                        {
                                                            add_pred(   /* R.1:1.0:0.1:1.0:1.0:0.0:1.1:1 */
                                                                0.16471571405955748);
                                                            if (defined_attr(0))    /* R.1:1.0:0.1:1.0:1.0:0.0:1.1:1.0 */
                                                            {
                                                                if (double_attr(0) <= 103.5)
                                                                {
                                                                    add_pred(   /* R.1:1.0:0.1:1.0:1.0:0.0:1.1:1.0:0 */
                                                                        -0.10753134195610406);
                                                                }
                                                                else
                                                                {
                                                                    add_pred(   /* R.1:1.0:0.1:1.0:1.0:0.0:1.1:1.0:1 */
                                                                        1.2830513923291085);
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                        else
                                        {
                                            add_pred(   /* R.1:1.0:0.1:1.0:1.0:1 */
                                                2.619712171051415);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                else
                {
                    add_pred(   /* R.1:1.0:1 */
                        -2.1720156931028796);
                    if (defined_attr(2))    /* R.1:1.0:1.0 */
                    {
                        if (double_attr(2) <= 183.5)
                        {
                            add_pred(   /* R.1:1.0:1.0:0 */
                                -2.2477102395197126);
                        }
                        else
                        {
                            add_pred(   /* R.1:1.0:1.0:1 */
                                0.23063596500597094);
                            if (defined_attr(2))    /* R.1:1.0:1.0:1.0 */
                            {
                                if (double_attr(2) <= 214.5)
                                {
                                    add_pred(   /* R.1:1.0:1.0:1.0:0 */
                                        0.7680370338266722);
                                }
                                else
                                {
                                    add_pred(   /* R.1:1.0:1.0:1.0:1 */
                                        -0.8526431552431321);
                                    if (defined_attr(0))    /* R.1:1.0:1.0:1.0:1.0 */
                                    {
                                        if (double_attr(0) <= 146.5)
                                        {
                                            add_pred(   /* R.1:1.0:1.0:1.0:1.0:0 */
                                                -0.05104439414539499);
                                        }
                                        else
                                        {
                                            add_pred(   /* R.1:1.0:1.0:1.0:1.0:1 */
                                                -1.1397942726666483);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    if (defined_attr(2))    /* R.2 */
    {
        if (double_attr(2) <= 150.5)
        {
            add_pred(   /* R.2:0 */
                -0.938668573828474);
            if (defined_attr(1))    /* R.2:0.0 */
            {
                if (double_attr(1) <= 37.5)
                {
                    add_pred(   /* R.2:0.0:0 */
                        -3.1773988717245647);
                    if (defined_attr(2))    /* R.2:0.0:0.0 */
                    {
                        if (double_attr(2) <= 105.5)
                        {
                            add_pred(   /* R.2:0.0:0.0:0 */
                                -1.897562437480771);
                        }
                        else
                        {
                            add_pred(   /* R.2:0.0:0.0:1 */
                                0.22783835120932);
                        }
                    }
                }
                else
                {
                    add_pred(   /* R.2:0.0:1 */
                        0.1212034964617438);
                    if (defined_attr(0))    /* R.2:0.0:1.0 */
                    {
                        if (double_attr(0) <= 90.5)
                        {
                            add_pred(   /* R.2:0.0:1.0:0 */
                                -1.126757426983378);
                            if (defined_attr(2))    /* R.2:0.0:1.0:0.0 */
                            {
                                if (double_attr(2) <= 142.5)
                                {
                                    add_pred(   /* R.2:0.0:1.0:0.0:0 */
                                        -2.1221633947688137);
                                }
                                else
                                {
                                    add_pred(   /* R.2:0.0:1.0:0.0:1 */
                                        0.13286072071680072);
                                }
                            }
                        }
                        else
                        {
                            add_pred(   /* R.2:0.0:1.0:1 */
                                0.37508951750564384);
                        }
                    }
                }
            }
            if (defined_attr(2))    /* R.2:0.1 */
            {
                if (double_attr(2) <= 19.5)
                {
                    add_pred(   /* R.2:0.1:0 */
                        -1.6431335055201688);
                }
                else
                {
                    add_pred(   /* R.2:0.1:1 */
                        -0.0428530185665827);
                }
            }
        }
        else
        {
            add_pred(   /* R.2:1 */
                0.3517901676996423);
            if (defined_attr(1))    /* R.2:1.0 */
            {
                if (double_attr(1) <= 104.5)
                {
                    add_pred(   /* R.2:1.0:0 */
                        0.12824907099683117);
                    if (defined_attr(2))    /* R.2:1.0:0.0 */
                    {
                        if (double_attr(2) <= 166.5)
                        {
                            add_pred(   /* R.2:1.0:0.0:0 */
                                -0.6938751180594588);
                            if (defined_attr(1))    /* R.2:1.0:0.0:0.0 */
                            {
                                if (double_attr(1) <= 42.5)
                                {
                                    add_pred(   /* R.2:1.0:0.0:0.0:0 */
                                        -1.5919642820180444);
                                }
                                else
                                {
                                    add_pred(   /* R.2:1.0:0.0:0.0:1 */
                                        0.11242796583377784);
                                }
                            }
                        }
                        else
                        {
                            add_pred(   /* R.2:1.0:0.0:1 */
                                0.06110356958447252);
                        }
                    }
                }
                else
                {
                    add_pred(   /* R.2:1.0:1 */
                        -2.7890754338347628);
                }
            }
        }
    }
    return finalize_pred();
}
