/* Auto-generated by genmsg_cpp for file /home/uwstereo/fuerte_workspace/sandbox/stingray-2-0/vision_port/msg/visionResult.msg */
#ifndef VISION_PORT_MESSAGE_VISIONRESULT_H
#define VISION_PORT_MESSAGE_VISIONRESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace vision_port
{
template <class ContainerAllocator>
struct visionResult_ {
  typedef visionResult_<ContainerAllocator> Type;

  visionResult_()
  : result(0)
  {
  }

  visionResult_(const ContainerAllocator& _alloc)
  : result(0)
  {
  }

  typedef int32_t _result_type;
  int32_t result;


  typedef boost::shared_ptr< ::vision_port::visionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_port::visionResult_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct visionResult
typedef  ::vision_port::visionResult_<std::allocator<void> > visionResult;

typedef boost::shared_ptr< ::vision_port::visionResult> visionResultPtr;
typedef boost::shared_ptr< ::vision_port::visionResult const> visionResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::vision_port::visionResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::vision_port::visionResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace vision_port

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vision_port::visionResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vision_port::visionResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vision_port::visionResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const  ::vision_port::visionResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_port::visionResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vision_port/visionResult";
  }

  static const char* value(const  ::vision_port::visionResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vision_port::visionResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Result definition.\n\
int32 result\n\
\n\
";
  }

  static const char* value(const  ::vision_port::visionResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::vision_port::visionResult_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vision_port::visionResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.result);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct visionResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_port::visionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::vision_port::visionResult_<ContainerAllocator> & v) 
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};


} // namespace message_operations
} // namespace ros

#endif // VISION_PORT_MESSAGE_VISIONRESULT_H

