/* Auto-generated by genmsg_cpp for file /home/uwstereo/fuerte_workspace/sandbox/stingray-2-0/vision_port/msg/visionAction.msg */
#ifndef VISION_PORT_MESSAGE_VISIONACTION_H
#define VISION_PORT_MESSAGE_VISIONACTION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "vision_port/visionActionGoal.h"
#include "vision_port/visionActionResult.h"
#include "vision_port/visionActionFeedback.h"

namespace vision_port
{
template <class ContainerAllocator>
struct visionAction_ {
  typedef visionAction_<ContainerAllocator> Type;

  visionAction_()
  : action_goal()
  , action_result()
  , action_feedback()
  {
  }

  visionAction_(const ContainerAllocator& _alloc)
  : action_goal(_alloc)
  , action_result(_alloc)
  , action_feedback(_alloc)
  {
  }

  typedef  ::vision_port::visionActionGoal_<ContainerAllocator>  _action_goal_type;
   ::vision_port::visionActionGoal_<ContainerAllocator>  action_goal;

  typedef  ::vision_port::visionActionResult_<ContainerAllocator>  _action_result_type;
   ::vision_port::visionActionResult_<ContainerAllocator>  action_result;

  typedef  ::vision_port::visionActionFeedback_<ContainerAllocator>  _action_feedback_type;
   ::vision_port::visionActionFeedback_<ContainerAllocator>  action_feedback;


  typedef boost::shared_ptr< ::vision_port::visionAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_port::visionAction_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct visionAction
typedef  ::vision_port::visionAction_<std::allocator<void> > visionAction;

typedef boost::shared_ptr< ::vision_port::visionAction> visionActionPtr;
typedef boost::shared_ptr< ::vision_port::visionAction const> visionActionConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::vision_port::visionAction_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::vision_port::visionAction_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace vision_port

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vision_port::visionAction_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vision_port::visionAction_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vision_port::visionAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8c1d51495ec77c696fffbfeb0811ad0a";
  }

  static const char* value(const  ::vision_port::visionAction_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x8c1d51495ec77c69ULL;
  static const uint64_t static_value2 = 0x6fffbfeb0811ad0aULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_port::visionAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vision_port/visionAction";
  }

  static const char* value(const  ::vision_port::visionAction_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vision_port::visionAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
visionActionGoal action_goal\n\
visionActionResult action_result\n\
visionActionFeedback action_feedback\n\
\n\
================================================================================\n\
MSG: vision_port/visionActionGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
visionGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: vision_port/visionGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Goal definition.\n\
int32 task\n\
\n\
================================================================================\n\
MSG: vision_port/visionActionResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
visionResult result\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalStatus\n\
GoalID goal_id\n\
uint8 status\n\
uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n\
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n\
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n\
                            #   and has since completed its execution (Terminal State)\n\
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n\
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n\
                            #    to some failure (Terminal State)\n\
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n\
                            #    because the goal was unattainable or invalid (Terminal State)\n\
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n\
                            #    and has not yet completed execution\n\
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n\
                            #    but the action server has not yet confirmed that the goal is canceled\n\
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n\
                            #    and was successfully cancelled (Terminal State)\n\
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n\
                            #    sent over the wire by an action server\n\
\n\
#Allow for the user to associate a string with GoalStatus for debugging\n\
string text\n\
\n\
\n\
================================================================================\n\
MSG: vision_port/visionResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Result definition.\n\
int32 result\n\
\n\
================================================================================\n\
MSG: vision_port/visionActionFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
visionFeedback feedback\n\
\n\
================================================================================\n\
MSG: vision_port/visionFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Feedback definition.\n\
int32 subtask\n\
\n\
\n\
";
  }

  static const char* value(const  ::vision_port::visionAction_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vision_port::visionAction_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.action_goal);
    stream.next(m.action_result);
    stream.next(m.action_feedback);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct visionAction_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_port::visionAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::vision_port::visionAction_<ContainerAllocator> & v) 
  {
    s << indent << "action_goal: ";
s << std::endl;
    Printer< ::vision_port::visionActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
s << std::endl;
    Printer< ::vision_port::visionActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
s << std::endl;
    Printer< ::vision_port::visionActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};


} // namespace message_operations
} // namespace ros

#endif // VISION_PORT_MESSAGE_VISIONACTION_H

