/* Auto-generated by genmsg_cpp for file /home/uwstereo/fuerte_workspace/sandbox/stingray-2-0/vision_port/msg/visionGoal.msg */
#ifndef VISION_PORT_MESSAGE_VISIONGOAL_H
#define VISION_PORT_MESSAGE_VISIONGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace vision_port
{
template <class ContainerAllocator>
struct visionGoal_ {
  typedef visionGoal_<ContainerAllocator> Type;

  visionGoal_()
  : task(0)
  {
  }

  visionGoal_(const ContainerAllocator& _alloc)
  : task(0)
  {
  }

  typedef int32_t _task_type;
  int32_t task;


  typedef boost::shared_ptr< ::vision_port::visionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_port::visionGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct visionGoal
typedef  ::vision_port::visionGoal_<std::allocator<void> > visionGoal;

typedef boost::shared_ptr< ::vision_port::visionGoal> visionGoalPtr;
typedef boost::shared_ptr< ::vision_port::visionGoal const> visionGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::vision_port::visionGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::vision_port::visionGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace vision_port

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vision_port::visionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vision_port::visionGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vision_port::visionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cd066b224c12460560bc3600f2c17041";
  }

  static const char* value(const  ::vision_port::visionGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xcd066b224c124605ULL;
  static const uint64_t static_value2 = 0x60bc3600f2c17041ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_port::visionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vision_port/visionGoal";
  }

  static const char* value(const  ::vision_port::visionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vision_port::visionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Goal definition.\n\
int32 task\n\
\n\
";
  }

  static const char* value(const  ::vision_port::visionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::vision_port::visionGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vision_port::visionGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.task);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct visionGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_port::visionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::vision_port::visionGoal_<ContainerAllocator> & v) 
  {
    s << indent << "task: ";
    Printer<int32_t>::stream(s, indent + "  ", v.task);
  }
};


} // namespace message_operations
} // namespace ros

#endif // VISION_PORT_MESSAGE_VISIONGOAL_H

