"""autogenerated by genpy from mission_controller/TargetWaypoints.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class TargetWaypoints(genpy.Message):
  _md5sum = "6ef3b92c6a5c0d62a34442009ffdad56"
  _type = "mission_controller/TargetWaypoints"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 target_surge
float64 target_lat
float64 target_lon
float64 target_depth

"""
  __slots__ = ['target_surge','target_lat','target_lon','target_depth']
  _slot_types = ['float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       target_surge,target_lat,target_lon,target_depth

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TargetWaypoints, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.target_surge is None:
        self.target_surge = 0.
      if self.target_lat is None:
        self.target_lat = 0.
      if self.target_lon is None:
        self.target_lon = 0.
      if self.target_depth is None:
        self.target_depth = 0.
    else:
      self.target_surge = 0.
      self.target_lat = 0.
      self.target_lon = 0.
      self.target_depth = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4d.pack(_x.target_surge, _x.target_lat, _x.target_lon, _x.target_depth))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.target_surge, _x.target_lat, _x.target_lon, _x.target_depth,) = _struct_4d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4d.pack(_x.target_surge, _x.target_lat, _x.target_lon, _x.target_depth))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.target_surge, _x.target_lat, _x.target_lon, _x.target_depth,) = _struct_4d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4d = struct.Struct("<4d")
