#include <stdlib.h>
#include <features.h>
#include <bits/predefs.h>
#include <sys/cdefs.h>
#include <bits/wordsize.h>
#include <gnu/stubs.h>
#include <gnu/stubs-32.h>
//#include <usr/lib/gcc/i686-linux-gnu/4.4.5/include/stddef.h>
#include <stddef.h>
#include <bits/waitflags.h>
//#include <bits/waitstatus.h>
#include <endian.h>
#include <bits/endian.h>
#include <bits/byteswap.h>
#include <sys/types.h>
#include <bits/types.h>
#include <bits/typesizes.h>
#include <time.h>
#include <sys/select.h>
#include <bits/select.h>
#include <bits/sigset.h>
#include <bits/time.h>
#include <sys/sysmacros.h>
#include <bits/pthreadtypes.h>
#include <alloca.h>
#include <stdio.h>
#include <libio.h>
#include <_G_config.h>
#include <wchar.h>
//#include <usr/lib/gcc/i686-linux-gnu/4.4.5/include/stdarg.h>
#include <stdarg.h>
#include <bits/stdio_lim.h>
#include <bits/sys_errlist.h>
#include <string.h>
#include <xlocale.h>
#include <sys/ioctl.h>
#include <bits/ioctls.h>
#include <asm/ioctls.h>
#include <asm-generic/ioctls.h>
#include <linux/ioctl.h>
#include <asm/ioctl.h>
#include <asm-generic/ioctl.h>
//#include <bits/ioctl-types.h>
#include <sys/ttydefaults.h>
#include <sys/stat.h>
#include <bits/stat.h>
#include <asm/types.h>
#include <asm-generic/types.h>
#include <asm-generic/int-ll64.h>
#include <asm/bitsperlong.h>
#include <asm-generic/bitsperlong.h>
#include <fcntl.h>
//#include <bits/fcntl.h>
#include <unistd.h>
#include <bits/posix_opt.h>
#include <bits/environments.h>
// #include <bits/confname.h>
#include <getopt.h>
#include <errno.h>
#include <bits/errno.h>
#include <linux/errno.h>
#include <asm/errno.h>
#include <asm-generic/errno.h>
#include <asm-generic/errno-base.h>
#include <hid.h>
#include <usb.h>
#include <stdint.h>
#include <bits/wchar.h>
//#include <usr/lib/gcc/i686-linux-gnu/4.4.5/include-fixed/limits.h>
#include <limits.h>
//#include <usr/lib/gcc/i686-linux-gnu/4.4.5/include-fixed/syslimits.h>
#include <syslimits.h>
#include <limits.h>
#include <bits/posix1_lim.h>
#include <bits/local_lim.h>
#include <linux/limits.h>
#include <bits/posix2_lim.h>
#include <sys/param.h>
#include <linux/param.h>
#include <asm/param.h>
#include <asm-generic/param.h>
#include <dirent.h>
//#include <bits/dirent.h>
#include <hidparser.h>
#include <hidtypes.h>
