/* Auto-generated by genmsg_cpp for file /home/perry/fuerte_workspace/sandbox/stingray-2-0/state_estimator/msg/SimDVLData.msg */
#ifndef STATE_ESTIMATOR_MESSAGE_SIMDVLDATA_H
#define STATE_ESTIMATOR_MESSAGE_SIMDVLDATA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace state_estimator
{
template <class ContainerAllocator>
struct SimDVLData_ {
  typedef SimDVLData_<ContainerAllocator> Type;

  SimDVLData_()
  : header()
  , surge(0.0)
  , sway(0.0)
  , heave(0.0)
  , altitude(0.0)
  {
  }

  SimDVLData_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , surge(0.0)
  , sway(0.0)
  , heave(0.0)
  , altitude(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _surge_type;
  float surge;

  typedef float _sway_type;
  float sway;

  typedef float _heave_type;
  float heave;

  typedef float _altitude_type;
  float altitude;


  typedef boost::shared_ptr< ::state_estimator::SimDVLData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::state_estimator::SimDVLData_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SimDVLData
typedef  ::state_estimator::SimDVLData_<std::allocator<void> > SimDVLData;

typedef boost::shared_ptr< ::state_estimator::SimDVLData> SimDVLDataPtr;
typedef boost::shared_ptr< ::state_estimator::SimDVLData const> SimDVLDataConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::state_estimator::SimDVLData_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::state_estimator::SimDVLData_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace state_estimator

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::state_estimator::SimDVLData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::state_estimator::SimDVLData_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::state_estimator::SimDVLData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7a37cc100a2e4608bcf0bcadc3a7a430";
  }

  static const char* value(const  ::state_estimator::SimDVLData_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x7a37cc100a2e4608ULL;
  static const uint64_t static_value2 = 0xbcf0bcadc3a7a430ULL;
};

template<class ContainerAllocator>
struct DataType< ::state_estimator::SimDVLData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "state_estimator/SimDVLData";
  }

  static const char* value(const  ::state_estimator::SimDVLData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::state_estimator::SimDVLData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float32 surge\n\
float32 sway\n\
float32 heave\n\
float32 altitude\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::state_estimator::SimDVLData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::state_estimator::SimDVLData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::state_estimator::SimDVLData_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::state_estimator::SimDVLData_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.surge);
    stream.next(m.sway);
    stream.next(m.heave);
    stream.next(m.altitude);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SimDVLData_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::state_estimator::SimDVLData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::state_estimator::SimDVLData_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "surge: ";
    Printer<float>::stream(s, indent + "  ", v.surge);
    s << indent << "sway: ";
    Printer<float>::stream(s, indent + "  ", v.sway);
    s << indent << "heave: ";
    Printer<float>::stream(s, indent + "  ", v.heave);
    s << indent << "altitude: ";
    Printer<float>::stream(s, indent + "  ", v.altitude);
  }
};


} // namespace message_operations
} // namespace ros

#endif // STATE_ESTIMATOR_MESSAGE_SIMDVLDATA_H

