"""autogenerated by genpy from sbBTA252/SBBTA252Data.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SBBTA252Data(genpy.Message):
  _md5sum = "2681e203ad008d492c8f38edd7805fd9"
  _type = "sbBTA252/SBBTA252Data"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 speed
float32 current
float32 motor_temp
float32 controller_temp
float32 controller_volt
float32 water

"""
  __slots__ = ['speed','current','motor_temp','controller_temp','controller_volt','water']
  _slot_types = ['float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       speed,current,motor_temp,controller_temp,controller_volt,water

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SBBTA252Data, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.speed is None:
        self.speed = 0.
      if self.current is None:
        self.current = 0.
      if self.motor_temp is None:
        self.motor_temp = 0.
      if self.controller_temp is None:
        self.controller_temp = 0.
      if self.controller_volt is None:
        self.controller_volt = 0.
      if self.water is None:
        self.water = 0.
    else:
      self.speed = 0.
      self.current = 0.
      self.motor_temp = 0.
      self.controller_temp = 0.
      self.controller_volt = 0.
      self.water = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_6f.pack(_x.speed, _x.current, _x.motor_temp, _x.controller_temp, _x.controller_volt, _x.water))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.speed, _x.current, _x.motor_temp, _x.controller_temp, _x.controller_volt, _x.water,) = _struct_6f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_6f.pack(_x.speed, _x.current, _x.motor_temp, _x.controller_temp, _x.controller_volt, _x.water))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.speed, _x.current, _x.motor_temp, _x.controller_temp, _x.controller_volt, _x.water,) = _struct_6f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6f = struct.Struct("<6f")
