; Auto-generated. Do not edit!


(cl:in-package vision_port-msg)


;//! \htmlinclude visionGoal.msg.html

(cl:defclass <visionGoal> (roslisp-msg-protocol:ros-message)
  ((task
    :reader task
    :initarg :task
    :type cl:integer
    :initform 0))
)

(cl:defclass visionGoal (<visionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <visionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'visionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name vision_port-msg:<visionGoal> is deprecated: use vision_port-msg:visionGoal instead.")))

(cl:ensure-generic-function 'task-val :lambda-list '(m))
(cl:defmethod task-val ((m <visionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader vision_port-msg:task-val is deprecated.  Use vision_port-msg:task instead.")
  (task m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <visionGoal>) ostream)
  "Serializes a message object of type '<visionGoal>"
  (cl:let* ((signed (cl:slot-value msg 'task)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <visionGoal>) istream)
  "Deserializes a message object of type '<visionGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'task) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<visionGoal>)))
  "Returns string type for a message object of type '<visionGoal>"
  "vision_port/visionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'visionGoal)))
  "Returns string type for a message object of type 'visionGoal"
  "vision_port/visionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<visionGoal>)))
  "Returns md5sum for a message object of type '<visionGoal>"
  "cd066b224c12460560bc3600f2c17041")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'visionGoal)))
  "Returns md5sum for a message object of type 'visionGoal"
  "cd066b224c12460560bc3600f2c17041")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<visionGoal>)))
  "Returns full string definition for message of type '<visionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal definition.~%int32 task~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'visionGoal)))
  "Returns full string definition for message of type 'visionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal definition.~%int32 task~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <visionGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <visionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'visionGoal
    (cl:cons ':task (task msg))
))
