; Auto-generated. Do not edit!


(cl:in-package vision_port-msg)


;//! \htmlinclude visionFeedback.msg.html

(cl:defclass <visionFeedback> (roslisp-msg-protocol:ros-message)
  ((subtask
    :reader subtask
    :initarg :subtask
    :type cl:integer
    :initform 0))
)

(cl:defclass visionFeedback (<visionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <visionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'visionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name vision_port-msg:<visionFeedback> is deprecated: use vision_port-msg:visionFeedback instead.")))

(cl:ensure-generic-function 'subtask-val :lambda-list '(m))
(cl:defmethod subtask-val ((m <visionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader vision_port-msg:subtask-val is deprecated.  Use vision_port-msg:subtask instead.")
  (subtask m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <visionFeedback>) ostream)
  "Serializes a message object of type '<visionFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'subtask)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <visionFeedback>) istream)
  "Deserializes a message object of type '<visionFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'subtask) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<visionFeedback>)))
  "Returns string type for a message object of type '<visionFeedback>"
  "vision_port/visionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'visionFeedback)))
  "Returns string type for a message object of type 'visionFeedback"
  "vision_port/visionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<visionFeedback>)))
  "Returns md5sum for a message object of type '<visionFeedback>"
  "d3b6cb31902dafaf24ff7219e217108a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'visionFeedback)))
  "Returns md5sum for a message object of type 'visionFeedback"
  "d3b6cb31902dafaf24ff7219e217108a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<visionFeedback>)))
  "Returns full string definition for message of type '<visionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback definition.~%int32 subtask~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'visionFeedback)))
  "Returns full string definition for message of type 'visionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback definition.~%int32 subtask~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <visionFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <visionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'visionFeedback
    (cl:cons ':subtask (subtask msg))
))
