(cl:defpackage state_estimator-msg
  (:use )
  (:export
<<<<<<< HEAD
   "<LOADTORQUE>"
   "LOADTORQUE"
   "<STATE>"
   "STATE"
   "<SIMDVLDATA>"
   "SIMDVLDATA"
   "<PRIMEPOWERSTARTSTOP>"
   "PRIMEPOWERSTARTSTOP"
   "<STATEPREDICTION>"
   "STATEPREDICTION"
   "<CONTROLINPUTS>"
   "CONTROLINPUTS"
=======
   "<STATEPREDICTION>"
   "STATEPREDICTION"
   "<SIMDVLDATA>"
   "SIMDVLDATA"
   "<STATE>"
   "STATE"
   "<CONTROLINPUTS>"
   "CONTROLINPUTS"
   "<LOADTORQUE>"
   "LOADTORQUE"
   "<PRIMEPOWERSTARTSTOP>"
   "PRIMEPOWERSTARTSTOP"
>>>>>>> ddc2ab950663a2edcc5d16708bce3684d5e6b40a
  ))

