(cl:in-package state_estimator-msg)
(cl:export '(HEADER-VAL
          HEADER
          LAT-VAL
          LAT
          LON-VAL
          LON
          DEPTH-VAL
          DEPTH
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          SURGE-VAL
          SURGE
          SWAY-VAL
          SWAY
          HEAVE-VAL
          HEAVE
          SURGE_DOT-VAL
          SURGE_DOT
          SWAY_DOT-VAL
          SWAY_DOT
          HEAVE_DOT-VAL
          HEAVE_DOT
          MAG_X-VAL
          MAG_X
          MAG_Y-VAL
          MAG_Y
          MAG_Z-VAL
          MAG_Z
))